# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches:
      - 'master'

  workflow_dispatch:

  schedule:
    - cron:  '0 10 * * 1'
    # 7日ごとに実行

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    env:
      GOOGLE_SHEET_API_KEY: ${{ secrets.GOOGLE_SHEET_API_KEY }}
      GOOGLE_SHEET_URL: ${{ secrets.GOOGLE_SHEET_URL }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - uses: actions/cache@v3
      id: node_modules_cache_id
      env:
        cache-name: cache-node-modules
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
    - run: echo '${{ toJSON(steps.node_modules_cache_id.outputs) }}'
    - if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
      run: npm install

    - name: Download data and set up environment variables
      run: |
        node bin/download.js ${GOOGLE_SHEET_URL} ${GOOGLE_SHEET_API_KEY}
        node bin/config.js

    - name: Build PWA Assets
      run: |
        npm run build:assets

    - name: Push the data to Github
      run: |
        git config --local user.name github-actions[bot]
        git config --local user.email github-actions[bot]@users.noreply.github.com
        if (git diff --shortstat | grep '[0-9]'); then \
          git add .; \
          git status .; \
          git commit -m "スプレッドシートのデータを更新"; \
          git push -f origin master; \
        fi

    - run: npm run build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.4.2
      with:
        branch: 'gh-pages'
        folder: './build/'
        target-folder: './'
